version: '3.7'
services:
  modelapi:
    build:
      context: modelapi
    volumes:
      - ./modelapi:/app/
    env_file:
      - ".env.modelapi"
    #ports:
    #  - 5000:5000

  nginx:
    build:
      context: nginx
    ports:
      - 5000:80
    restart: unless-stopped
    depends_on:
      - modelapi

  redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped

  hospital:
    build:
      context: hospital
    volumes:
      - ./hospital/:/app/
      - ./patient_data/:/data/
    env_file:
       - ".env.hospital"
    restart: unless-stopped
    ports:
      - 8080:8080

  buffer:
    build:
        context: buffer
    volumes:
      - ./buffer:/app/
    env_file:
      - ".env.buffer"
    links:
      - redis
    depends_on:
      #- redis
      - hospital
    restart: on-failure

  tool:
    build:
        context: tool
    volumes:
      - ./tool:/app/
    env_file:
      - ".env.tool"
    links:
      - tooldb:db
      - redis
    depends_on:
      #- redis
      - tooldb
    restart: on-failure

  tooldb:
    build:
      context: tool/database
    restart: unless-stopped
    env_file:
      - ".env.tooldb"
    ports:
      - "3306:3306"
    expose: ["3306"]
volumes:
  redis:
